import datetime

from sqlalchemy import Column, DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped

from app.database import Base

# ─── Users ──────────────────────────────────────────────────────────────────
# Stores login credentials and role assignment for all system users.


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False)
    password = Column(String(255), nullable=False)
    role = Column(String(20), nullable=False)


# ─── Patients ───────────────────────────────────────────────────────────────
# Tracks every patient across their lifecycle from Registration to Discharge.
# status transitions: Registered → Checked In → Admitted → Discharged.


class Patient(Base):
    __tablename__ = "patients"

    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(String(20), unique=True, nullable=False)
    name = Column(String(100), nullable=False)
    age = Column(Integer, nullable=False)
    gender = Column(String(10), nullable=False)
    department = Column(String(50), default="General")
    ward = Column(String(50), default="")
    assigned_doctor = Column(String(100), default="")
    assigned_nurse = Column(String(100), default="")
    status: Mapped[str] = Column(String(20), default="Registered")


# ─── Appointments ───────────────────────────────────────────────────────────


class Appointment(Base):
    __tablename__ = "appointments"

    id = Column(Integer, primary_key=True, index=True)
    appointment_id = Column(String(20), unique=True, nullable=False)
    patient_id = Column(String(20), nullable=False)
    date = Column(String(20), nullable=False)
    time = Column(String(20), nullable=False)
    status = Column(String(20), default="Scheduled")


# ─── Events ─────────────────────────────────────────────────────────────────
# Immutable audit log — every hospital action creates an event record.
# event_type values match the Event Routing Engine in engine/routing.py.


class Event(Base):
    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(String(20), unique=True, nullable=False)
    event_type = Column(String(50), nullable=False)
    patient_id = Column(String(20), nullable=False)
    description = Column(Text, default="")
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    status = Column(String(20), default="Pending")


# ─── Alerts ─────────────────────────────────────────────────────────────────
# Generated by the Risk Engine when vitals are outside normal ranges.
# severity can be Normal, Warning, or Critical.


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(20), unique=True, nullable=False)
    patient_id = Column(String(20), nullable=False)
    severity = Column(String(20), nullable=False)
    message = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    status = Column(String(20), default="Active")


# ─── Reviews ────────────────────────────────────────────────────────────────
# Doctor-submitted notes after reviewing a patient.


class Review(Base):
    __tablename__ = "reviews"

    id = Column(Integer, primary_key=True, index=True)
    review_id = Column(String(20), unique=True, nullable=False)
    patient_id = Column(String(20), nullable=False)
    doctor_id = Column(String(20), nullable=False)
    review_note = Column(Text, default="")
    review_status = Column(String(20), default="Pending")


# ─── Medications ────────────────────────────────────────────────────────────
# Tracks prescriptions from Prescribed → Administered lifecycle.


class Medication(Base):
    __tablename__ = "medications"

    id = Column(Integer, primary_key=True, index=True)
    medication_id = Column(String(20), unique=True, nullable=False)
    patient_id = Column(String(20), nullable=False)
    medicine_name = Column(String(100), nullable=False)
    prescribed_by = Column(String(100), nullable=False)
    status: Mapped[str] = Column(String(20), default="Prescribed")


# ─── Notifications ──────────────────────────────────────────────────────────
# In-app messages routed to specific roles by the Event Routing Engine.
# Drives the notification badges on each dashboard.


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    notification_id = Column(String(20), unique=True, nullable=False)
    source_event_id = Column(String(50), index=True)
    recipient_role = Column(String(20), nullable=False)
    message = Column(Text, nullable=False)
    status: Mapped[str] = Column(String(20), default="Unread")
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
